### ISSUE TITLE
Code suggestion seems not working

### ISSUE THREAD

**Issue by aztack** [Pab450/RunJS-Cracker#10]
Is that a known issue or is the code suggestion not supposed to work after cracking?

**Comment by Pab450** [comment]
<img width="332" alt="Capture d’écran 2024-04-21 à 17 55 20" src="https://github.com/Pab450/RunJS-Cracker/assets/16840900/d278af34-89b5-4c4c-bdc1-0b1b2a1458db">


Works for me, you need to activate it in the settings!

<img width="552" alt="Capture d’écran 2024-04-21 à 17 57 06" src="https://github.com/Pab450/RunJS-Cracker/assets/16840900/95918b06-42b6-4f10-a64a-4a491f407897">

**Comment by aztack** [comment]
@Pab450 Thanks! 
<img width="575" alt="image" src="https://github.com/Pab450/RunJS-Cracker/assets/782871/df604168-4b2f-4bee-9a2f-b862298adc74">
FYI: For library like 'lodash', you have to install the '@types/lodash' to make RunJS showing the autocomplete.
