### ISSUE TITLE
Persistent key problem

### ISSUE THREAD

**Issue by rahulmasal** [Pab450/RunJS-Cracker#2]
got alternative to this Quokka JS which is Best for JS developers! and supported most of code editors!

**Comment by Pab450** [comment]
Hi,

I will attempt to reproduce this behavior and see if I encounter the same issue. 
If I experience the same problem, I will explore the possibility of modifying the mapping to remove this verification.

I will keep you updated. 

Thank you for bringing this to our attention!

**Comment by Pab450** [comment]
I faced the same issue, but it doesn't actually prevent file saving, just a bit annoying. 

I'll try tweaking the mapping and possibly use a default key. 
I'll keep you posted on any updates. 

Thanks for pointing it out!

**Comment by Pab450** [comment]
It appears there's a persistent key issue. Sometimes, when I exit the software and return, I have to re-enter my activation key.

**Comment by leancerioli** [comment]
> It appears there's a persistent key issue. Sometimes, when I exit the software and return, I have to re-enter my activation key.

i have the same issue, when i relaunch RunJS i have to re-enter activation key

**Comment by rahulmasal** [comment]
Quokka Pro, Wallaby Pro crack, try to make it, or a trial resetter is also acceptable because these tools provide a fantastic playground for javascript, and tools are very high in price on a subscription basis. After installing it in vs code and then uninstalling and deleting it from the vs code folder, it is still not resetting for the new trial.

https://quokkajs.com/ && https://wallabyjs.com/

**Comment by Luca4316** [comment]
Thanks

**Comment by rahulmasal** [comment]
Quokka Pro and Wallaby Pro are the best tools for JAVASCRIPT.

Quokka.js runs JavaScript and TypeScript with instant feedback. Runtime values are updated and displayed in your editor next to your code, as you type.

Wallaby.js is a developer productivity tool that runs your JavaScript and TypeScript tests immediately as you type, highlighting results in your IDE right next to your code.

https://quokkajs.com/ && https://wallabyjs.com/

**Comment by Pab450** [comment]
I'll try to work on it and get a fix out before Christmas.

**Comment by rahulmasal** [comment]
I am using Quokka, which is better than RUNJS.

**Comment by mohitxskull** [comment]
thanks for this crack @Pab450

**Comment by Pab450** [comment]
Key persistence problem fixed in RunJS version 2.10.1. Update your RunJS & download the latest crack. @rahulmasal @leancerioli @mohitxskull

**Comment by mohitxskull** [comment]
Thank you!

**Comment by leancerioli** [comment]
Nice, thank you!!
