### ISSUE TITLE
RunJS 2.10 is out

### ISSUE THREAD

**Issue by Pab450** [Pab450/RunJS-Cracker#5]
2.10 was released a few hours ago, I'm going to try cracking this new version.

**Comment by Luca4316** [comment]
Already crack for me, i'm too strong i think, but i understand **### people who start** in coding

**Comment by Pab450** [comment]
I've managed to crack it but I'm obliged to use a 40 character key. I'd like to remove this check and set the key persistence issue.

**Comment by Pab450** [comment]
It seems I've managed to fix the persistent key issue and it's no longer necessary to enter a key.

**Comment by Pab450** [comment]
I've switched support to version 2.10.1, I'm not taking any chances by leaving the old mappings to avoid a conflict between versions.
