### ISSUE TITLE
Cracking process

### ISSUE THREAD

**Issue by z0xyz** [Pab450/RunJS-Cracker#6]
I've tried to crack RunJs before, but I was very baffled by the obfuscated code not understanding which portions of code are responsible for what. Would you suggest any other approach to handle such a task in general? (Not sure if I should open up an issue to ask for that)

**Comment by Pab450** [comment]
Hello @z0xyz,

Thank you for your interest and for bringing up this relevant question. I want to clarify that the code in RunJS is not obfuscated but rather minified. Minification was primarily employed to reduce the file size by shortening variable names.

Understanding minified code can be challenging, especially when variable names are shortened. However, unlike obfuscated code, the function and property names in RunJS have remained unchanged, making it easier to comprehend the program logic.

If you'd like to explore the RunJS source code in a more readable format, I recommend using an indenter to reformat the code. This can significantly enhance readability by properly aligning the code.

Regarding your question on the best approach to understand the code, I suggest focusing on a small portion of the code at a time. Utilize tools like indenters to make the code more readable and then identify specific functions or sections of interest. Analyze these parts of the code more thoroughly. This segmented approach can make the task more manageable.

if you have specific questions about particular parts of the code or if you need assistance in understanding a specific feature feel free to ask.

Best regards

**Comment by z0xyz** [comment]
@Pab450
Thanks for your thorough breakdown.

It's indeed a struggle to understand that code, with overlapping variable/function names all over the place, making navigation across the congested singular source file, but with this approach, things can become more doable.

My main points of struggle were
- Not being able to identify portions of the source (so it felt as If it was a hit-or-miss).
- Making the code readable inhibited repackaging it again to test run the changes made.
- Uncertainty (I was surprised to find that the solution was as straightforward as a regular expression find and replace).
- Repackaging to see how the changes affect the app (to understand code segments) was time-consuming.
