### ISSUE TITLE
2.11.0 is out 🎉 

### ISSUE THREAD

**Issue by Pab450** [Pab450/RunJS-Cracker#7]
Hello everyone! Hope you're all well! Crack support for version 2.11.0 is now available, the best change in this version is the use of regexes to maintain support for future versions. This version normally allows you to get the software with all the paid features, but I haven't had the time to check all, so don't hesitate to report a missing feature so that I can adapt the regexes accordingly...

**Comment by 592146505** [comment]
> 2.11 was released a few hours ago, I'm going to try cracking this new version.

Looking forward to your success. good luck

**Comment by Pab450** [comment]
Hello everyone! Hope you're all well! Crack support for version 2.11.0 is now available, the best change in this version is the use of regexes to maintain support for future versions. This version normally allows you to get the software with all the paid features, but I haven't had the time to check all, so don't hesitate to report a missing feature so that I can adapt the regexes accordingly...

**Comment by LordMoMA** [comment]
why I cannot activate the licence using the method? the activate is still there!
