### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tiagorangel2011** [Pab450/RunJS-Cracker#8]
When trying to access a license-restricted feature, I get this popup: 

![screenshot](https://github.com/Pab450/RunJS-Cracker/assets/70700766/c6ae5885-9408-47cf-a2d0-44aa9840775c)

**Comment by Pab450** [comment]
Hi, I think you're using the latest version of runJS when the supported version is 2.10.1... if that's the case please be careful to read the readme carefully to avoid spamming the repository. a crack for the latest version should be out soon I just have a lot of work on the side and haven't had time to go through runjs.

**Comment by tiagorangel2011** [comment]
Thank you for your reply! Can you please tell me how I can downgrade RunJS? I would love to help test the cracker :D

by the way I found a key-value pair related to the license activation in the JSON config of runjs itself, it might maybe help lol.

**Comment by Pab450** [comment]
> Thank you for your reply! Can you please tell me how I can downgrade RunJS? I would love to help test the cracker :D
> 
> by the way I found a key-value pair related to the license activation in the JSON config of runjs itself, it might maybe help lol.

No need to downgrade RunJS the latest version of the crack (the update was released yesterday) supports the latest version of RunJS (2.11.0), download the runJS crack repository and run the crack, follow all instructions in the readme. Make sure you've downloaded a clean version of RunJS to avoid conflicts. Nevertheless you can download any version of runjs you want [here](https://github.com/lukehaas/RunJS/releases).

**Comment by Pab450** [comment]
> by the way I found a key-value pair related to the license activation in the JSON config of runjs itself, it might maybe help lol.

Who needs a config file when you can just overwrite the source code? I'm practically inventing new features for RunJS over here :trollface:
