### ISSUE TITLE
2.11.0 not working

### ISSUE THREAD

**Issue by LordMoMA** [Pab450/RunJS-Cracker#9]
I followed the steps in this repo and everything was installed successfully (those npm stuff all done), but there is always the activate button there, and any random 12 digits cannot activate the app. 

I deleted the app and reinstalled again, opened and exited many times, not working.

May I know how to fix this?

**Comment by Pab450** [comment]
To better understand the situation, I would need some additional information. Could you please provide me with the following details:

1.     The version of runJS you are using.
2.     Your operating system and its version.
3.     Can you confirm that you have already launched the application for the first time and closed it before running the script?

It would be helpful to know the script's feedback when running it.

**Comment by LordMoMA** [comment]
thank you it worked, I followed your step 3, it worked! quite tricky!

**Comment by Pab450** [comment]
> thank you it worked, I followed your step 3, it worked! quite tricky!

Yeah it's a bit tricky but simply because without launching the app isn't really installed.
